# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    container_name: core-api
    restart: always
    build: .
    volumes:
      - ${PWD}:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    links:
      - database  
    depends_on:
      - database  
 
  database:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/${USER}/mongo/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: beldex123

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: beldex123